# Generated by Django 4.1.1 on 2022-10-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOSS', '0002_inventory_order_order_details_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
