# Generated by Django 4.1.1 on 2022-10-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOOSS', '0003_alter_payment_expiration_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Details',
            new_name='Order_Detail',
        ),
        migrations.RenameField(
            model_name='order_detail',
            old_name='order_details_id',
            new_name='order_detail_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order_details_id',
            new_name='order_detail_id',
        ),
    ]
