# Generated by Django 4.1.2 on 2022-10-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOOSS', '0005_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Fname',
            new_name='cust_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Lname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_name',
        ),
    ]
