# Generated by Django 4.1.1 on 2022-10-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOSS', '0006_rename_fname_customer_cust_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, upload_to='inventory/%Y/%m/%d'),
        ),
    ]
