# Generated by Django 4.1.1 on 2022-11-04 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TOOSS', '0007_inventory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TOOSS.user'),
        ),
    ]
