# Generated by Django 4.1.1 on 2022-11-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOSS', '0009_alter_customer_cust_name_alter_order_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
