# Generated by Django 4.1.1 on 2022-11-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOSS', '0011_alter_inventory_options_inventory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
