# Generated by Django 4.1.1 on 2022-11-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOOSS', '0013_order_detail_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='total_price',
        ),
    ]
