# Generated by Django 4.1.1 on 2022-11-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOOSS', '0015_remove_payment_card_number_remove_payment_ccv_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cc', 'Credit Card'), ('dc', 'Debit Card'), ('cs', 'Cash'), ('ch', 'Check'), ('bc', 'Bit Coin')], default='cc', max_length=2),
        ),
    ]
